worlds = [
    {
        "name": "Terramira",
        "default_block_id": 2,
        "size": 100,
    },
    {
        "name": "Aria",
        "default_block_id": 12,
        "size": 100,
    },
    {
        "name": "Infernium",
        "default_block_id": 18,
        "size": 100,
    },
]

blocks_type = [
    {
        "name": "Grass",
        "price": 0,
        "sturdiness": 1,
        "image": "grass.png",
        "world_id": 1,
        "vein_size": 1,
        "rarity": 0,
        "height_min": 0,
        "height_max": 0,
    },
    {
        "name": "Stone",
        "price": 1,
        "sturdiness": 3,
        "image": "stone.png",
        "world_id": 1,
        "vein_size": 1,
        "rarity": 0,
        "height_min": 0,
        "height_max": 0,
    },
    {
        "name": "Coal",
        "price": 1,
        "sturdiness": 5,
        "image": "coal_ore.png",
        "world_id": 1,
        "vein_size": 6,
        "rarity": 0.3,
        "height_min": 5,
        "height_max": 100,
    },
    {
        "name": "Iron",
        "price": 1,
        "sturdiness": 6,
        "image": "iron_ore.png",
        "world_id": 1,
        "vein_size": 5,
        "rarity": 0.28,
        "height_min": 5,
        "height_max": 100,
    },
    {
        "name": "Gold",
        "price": 1,
        "sturdiness": 6,
        "image": "gold_ore.png",
        "world_id": 1,
        "vein_size": 4,
        "rarity": 0.33,
        "height_min": 20,
        "height_max": 100,
    },
    {
        "name": "Diamond",
        "price": 1,
        "sturdiness": 8,
        "image": "diamond_ore.png",
        "world_id": 1,
        "vein_size": 3,
        "rarity": 0.35,
        "height_min": 30,
        "height_max": 100,
    },
    {
        "name": "Emerald",
        "price": 1,
        "sturdiness": 8,
        "image": "emerald_ore.png",
        "world_id": 1,
        "vein_size": 1,
        "rarity": 0.36,
        "height_min": 40,
        "height_max": 100,
    },
    {
        "name": "Ruby",
        "price": 1,
        "sturdiness": 8,
        "image": "ruby_ore.png",
        "world_id": 1,
        "vein_size": 2,
        "rarity": 0.36,
        "height_min": 50,
        "height_max": 100,
    },
    {
        "name": "Sapphire",
        "price": 1,
        "sturdiness": 8,
        "image": "sapphire_ore.png",
        "world_id": 1,
        "vein_size": 2,
        "rarity": 0.37,
        "height_min": 60,
        "height_max": 100,
    },
    {
        "name": "Amethyst",
        "price": 1,
        "sturdiness": 8,
        "image": "amethyst_ore.png",
        "world_id": 1,
        "vein_size": 3,
        "rarity": 0.38,
        "height_min": 70,
        "height_max": 100,
    },
    {
        "name": "Uranium",
        "price": 1,
        "sturdiness": 10,
        "image": "uranium_ore.png",
        "world_id": 1,
        "vein_size": 5,
        "rarity": 0.39,
        "height_min": 60,
        "height_max": 100,
    },
    {
        "name": "Relogith",
        "price": 1,
        "sturdiness": 10,
        "image": "regolith.png",
        "world_id": 2,
        "vein_size": 1,
        "rarity": 0,
        "height_min": 0,
        "height_max": 0,
    },
    {
        "name": "Chromite",
        "price": 1,
        "sturdiness": 11,
        "image": "chromite_ore.png",
        "world_id": 2,
        "vein_size": 5,
        "rarity": 0.28,
        "height_min": 5,
        "height_max": 100,
    },
    {
        "name": "Augite",
        "price": 1,
        "sturdiness": 11,
        "image": "augite_ore.png",
        "world_id": 2,
        "vein_size": 4,
        "rarity": 0.33,
        "height_min": 20,
        "height_max": 100,
    },
    {
        "name": "Enstatite",
        "price": 1,
        "sturdiness": 11,
        "image": "enstatite_ore.png",
        "world_id": 2,
        "vein_size": 3,
        "rarity": 0.35,
        "height_min": 30,
        "height_max": 100,
    },
    {
        "name": "Hercynite",
        "price": 1,
        "sturdiness": 11,
        "image": "hercynite_ore.png",
        "world_id": 2,
        "vein_size": 1,
        "rarity": 0.36,
        "height_min": 40,
        "height_max": 100,
    },
    {
        "name": "Troilite",
        "price": 1,
        "sturdiness": 11,
        "image": "troilite_ore.png",
        "world_id": 2,
        "vein_size": 2,
        "rarity": 0.36,
        "height_min": 50,
        "height_max": 100,
    },
    {
        "name": "Quartzite",
        "price": 1,
        "sturdiness": 13,
        "image": "quartzite.png",
        "world_id": 3,
        "vein_size": 1,
        "rarity": 0,
        "height_min": 0,
        "height_max": 0,
    },
    {
        "name": "Dravite",
        "price": 1,
        "sturdiness": 13,
        "image": "dravite_ore.png",
        "world_id": 3,
        "vein_size": 6,
        "rarity": 0.28,
        "height_min": 5,
        "height_max": 100,
    },
    {
        "name": "Yttrium",
        "price": 1,
        "sturdiness": 13,
        "image": "yttrium_ore.png",
        "world_id": 3,
        "vein_size": 4,
        "rarity": 0.33,
        "height_min": 5,
        "height_max": 100,
    },
    {
        "name": "Rubidium",
        "price": 1,
        "sturdiness": 13,
        "image": "rubidium_ore.png",
        "world_id": 3,
        "vein_size": 4,
        "rarity": 0.35,
        "height_min": 20,
        "height_max": 100,
    },
    {
        "name": "Strontium",
        "price": 1,
        "sturdiness": 15,
        "image": "strontium_ore.png",
        "world_id": 3,
        "vein_size": 3,
        "rarity": 0.36,
        "height_min": 30,
        "height_max": 100,
    },
    {
        "name": "Iridum",
        "price": 1,
        "sturdiness": 15,
        "image": "iridium_ore.png",
        "world_id": 3,
        "vein_size": 1,
        "rarity": 0.36,
        "height_min": 40,
        "height_max": 100,
    },
    {
        "name": "Bedrock",
        "price": 1,
        "sturdiness": 10000000000000,
        "image": "bedrock.png",
        "world_id": 0,
        "vein_size": 1,
        "rarity": 0,
        "height_min": 0,
        "height_max": 0,
    },
]


Allpickaxes = [
    {
        "name": "Basic Pickaxe",
        "price": 0,
        "description": "Its basic.",
        "mining_speed": 1,
        "enchant_id": 0,
        "break_chance": 100,
        "image": "pickaxes/1.png",
    },
    {
        "name": "Stone Pickaxe",
        "price": 20,
        "description": "Stony.",
        "mining_speed": 1.1,
        "enchant_id": 0,
        "break_chance": 0,
        "image": "pickaxes/2.png",
    },
    {
        "name": "Steel Pickaxe",
        "price": 30,
        "description": "Fe + C = ?.",
        "mining_speed": 1.2,
        "enchant_id": 0,
        "break_chance": 0,
        "image": "pickaxes/3.png",
    },
    {
        "name": "Aluminium Pickaxe",
        "price": 50,
        "description": "Very light.",
        "mining_speed": 1.3,
        "enchant_id": 0,
        "break_chance": 0,
        "image": "pickaxes/4.png",
    },
    {
        "name": "Diamond Pickaxe",
        "price": 75,
        "description": "Diamonds !.",
        "mining_speed": 1.4,
        "enchant_id": 0,
        "break_chance": 0,
        "image": "pickaxes/5.png",
    },
    {
        "name": "Magic Pickaxe",
        "price": 100,
        "description": "It's magic.",
        "mining_speed": 1.5,
        "enchant_id": 0,
        "break_chance": 0,
        "image": "pickaxes/6.png",
    },
    {
        "name": "Sledgehammer",
        "price": 120,
        "description": "Can smash rocks.",
        "mining_speed": 1.6,
        "enchant_id": 0,
        "break_chance": 0,
        "image": "pickaxes/7.png",
    },
    {
        "name": "Katana",
        "price": 150,
        "description": "Just a sword.",
        "mining_speed": 1.7,
        "enchant_id": 0,
        "break_chance": 0,
        "image": "pickaxes/8.png",
    },
    {
        "name": "Jackhammer",
        "price": 180,
        "description": "Needs electricity.",
        "mining_speed": 1.8,
        "enchant_id": 0,
        "break_chance": 0,
        "image": "pickaxes/9.png",
    },
    {
        "name": "Strange Pickaxe",
        "price": 200,
        "description": "It's quite strange.",
        "mining_speed": 1.9,
        "enchant_id": 0,
        "break_chance": 0,
        "image": "pickaxes/10.png",
    },
    {
        "name": "THE PICKAXE OF DOOM",
        "price": 250,
        "description": "It's all in the name.",
        "mining_speed": 2,
        "enchant_id": 0,
        "break_chance": 0,
        "image": "pickaxes/11.png",
    },
    {
        "name": "Nuclear Pickaxe",
        "price": 300,
        "description": "Tastes like candy.",
        "mining_speed": 2.1,
        "enchant_id": 0,
        "break_chance": 0,
        "image": "pickaxes/12.png",
    },
    {
        "name": "Dark Mass",
        "price": 350,
        "description": "Not heavier than your mom.",
        "mining_speed": 2.2,
        "enchant_id": 0,
        "break_chance": 0,
        "image": "pickaxes/13.png",
    },
    {
        "name": "Lightsaber",
        "price": 400,
        "description": "May the 4th be with you.",
        "mining_speed": 2.3,
        "enchant_id": 0,
        "break_chance": 0,
        "image": "pickaxes/14.png",
    },
    {
        "name": "Flaming Pickaxe",
        "price": 450,
        "description": "Don't touch it.",
        "mining_speed": 2.4,
        "enchant_id": 0,
        "break_chance": 0,
        "image": "pickaxes/15.png",
    },
    {
        "name": "Mythical Pickaxe",
        "price": 500,
        "description": "A pickaxe that can mine anything.",
        "mining_speed": 2.5,
        "enchant_id": 0,
        "break_chance": 0,
        "image": "pickaxes/16.png",
    },
    {
        "name": "Plasma Pickaxe",
        "price": 550,
        "description": "My dad say it looks cool.",
        "mining_speed": 2.6,
        "enchant_id": 0,
        "break_chance": 0,
        "image": "pickaxes/17.png",
    },
    {
        "name": "Rock Vaporizer",
        "price": 600,
        "description": "A pickaxe that can vaporize anything.",
        "mining_speed": 2.7,
        "enchant_id": 0,
        "break_chance": 0,
        "image": "pickaxes/18.png",
    },
    {
        "name": "Thor's Hammer",
        "price": 650,
        "description": "Only the brave ones can lift it.",
        "mining_speed": 2.8,
        "enchant_id": 0,
        "break_chance": 0,
        "image": "pickaxes/19.png",
    },
    {
        "name": "Lucky Charm",
        "price": 700,
        "description": "Charming.",
        "mining_speed": 2.9,
        "enchant_id": 0,
        "break_chance": 0,
        "image": "pickaxes/20.png",
    },
    {
        "name": "Comically Large Spoon",
        "price": 750,
        "description": "Looks goofy.",
        "mining_speed": 3,
        "enchant_id": 0,
        "break_chance": 0,
        "image": "pickaxes/21.png",
    },
    {
        "name": "Haunted Pickaxe",
        "price": 1000,
        "description": "Scary isnt it ?",
        "mining_speed": 3.3,
        "enchant_id": 0,
        "break_chance": 0,
        "image": "pickaxes/22.png",
    },
    {
        "name": "Godly Pickaxe",
        "price": 1500,
        "description": "All in the name.",
        "mining_speed": 3.6,
        "enchant_id": 0,
        "break_chance": 0,
        "image": "pickaxes/23.png",
    },
    {
        "name": "Nokia  3310",
        "price": 3000,
        "description": "A relic from the past.",
        "mining_speed": 5,
        "enchant_id": 0,
        "break_chance": 0,
        "image": "pickaxes/24.png",
    },
]

Allbackpacks = [
    {
        "name": "Small Backpack",
        "price": 100,
        "description": "A small backpack.",
        "capacity": 100,
        "image": "backpacks/1.png",
    },
    {
        "name": "Backpack",
        "price": 200,
        "description": "A basic backpack.",
        "capacity": 200,
        "image": "backpacks/2.png",
    },
    {
        "name": "Fair Backpack",
        "price": 300,
        "description": "A fair backpack.",
        "capacity": 300,
        "image": "backpacks/3.png",
    },
    {
        "name": "Large Backpack",
        "price": 400,
        "description": "A large backpack.",
        "capacity": 400,
        "image": "backpacks/not_found.png",
    },
    {
        "name": "Millitary Backpack",
        "price": 500,
        "description": "Can hold your rocket launcher.",
        "capacity": 500,
        "image": "backpacks/not_found.png",
    },
    {
        "name": "Barrel",
        "price": 600,
        "description": "Thats a barrel ! Yargh.",
        "capacity": 600,
        "image": "backpacks/not_found.png",
    },
    {
        "name": "Fridge",
        "price": 700,
        "description": "Good luck carrying it around.",
        "capacity": 700,
        "image": "backpacks/not_found.png",
    },
    {
        "name": "Magic Backpack",
        "price": 800,
        "description": "I stole it to a magician.",
        "capacity": 800,
        "image": "backpacks/not_found.png",
    },
    {
        "name": "Boeing 747",
        "price": 800,
        "description": "I believe i can fly.",
        "capacity": 911,
        "image": "backpacks/not_found.png",
    },
    {
        "name": "Godly Backpack",
        "price": 1000,
        "description": "Used to be Zeus'.",
        "capacity": 1000,
        "image": "backpacks/not_found.png",
    },
    {
        "name": "Comically Large Box",
        "price": 1100,
        "description": "Pretty goofy.",
        "capacity": 1100,
        "image": "backpacks/not_found.png",
    },
    {
        "name": "Cheops Backpack",
        "price": 5000,
        "description": "Uses the power of the cloud.",
        "capacity": 100000000000,
        "image": "backpacks/not_found.png",
    },
]

Allenchantments = {
    "none": {"name": "None", "price": 0, "description": "No enchantment.", "level": 0},
    "fortune_1": {
        "name": "Fortune",
        "price": 200,
        "description": "There is a small chance of duplicating the blocks that you mine.",
        "level": 1,
    },
    "fortune_2": {
        "name": "Fortune",
        "price": 400,
        "description": "There is a fair chance of duplicating the blocks that you mine.",
        "level": 2,
    },
    "fortune_3": {
        "name": "Fortune",
        "price": 600,
        "description": "There is a high chance of duplicating the blocks that you mine.",
        "level": 3,
    },
    "efficiency_1": {
        "name": "Efficiency",
        "price": 200,
        "description": "Your pickaxe will mine blocks a bit faster.",
        "level": 1,
    },
    "efficiency_2": {
        "name": "Efficiency",
        "price": 400,
        "description": "Your pickaxe will mine blocks faster.",
        "level": 2,
    },
    "efficiency_3": {
        "name": "Efficiency",
        "price": 600,
        "description": "Your pickaxe will mine blocks a lot faster.",
        "level": 3,
    },
    "unbreaking_1": {
        "name": "Unbreaking",
        "price": 200,
        "description": "When your pickaxe break you will get a slight chance to avoid it.",
        "level": 1,
    },
    "unbreaking_2": {
        "name": "Unbreaking",
        "price": 400,
        "description": "When your pickaxe break you will get a fair chance to avoid it.",
        "level": 2,
    },
    "unbreaking_3": {
        "name": "Unbreaking",
        "price": 600,
        "description": "When your pickaxe break you will get a high chance to avoid it.",
        "level": 3,
    },
}
